# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/szymon/Documents/ISAE/research_project/implemnetations/riscv_single_core/rv32i_sc.srcs/sources_1/ip/instruction_fetch_bram/instruction_fetch_bram.xci
# IP: The module: 'instruction_fetch_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/szymon/Documents/ISAE/research_project/implemnetations/riscv_single_core/rv32i_sc.gen/sources_1/ip/instruction_fetch_bram/instruction_fetch_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instruction_fetch_bram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/szymon/Documents/ISAE/research_project/implemnetations/riscv_single_core/rv32i_sc.srcs/sources_1/ip/instruction_fetch_bram/instruction_fetch_bram.xci
# IP: The module: 'instruction_fetch_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/szymon/Documents/ISAE/research_project/implemnetations/riscv_single_core/rv32i_sc.gen/sources_1/ip/instruction_fetch_bram/instruction_fetch_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instruction_fetch_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
